### ISSUE TITLE
run ptfce in matlab without .mat file?

### ISSUE THREAD

**Issue by janderz8** [spisakt/pTFCE#1]
Hi Tamás,

First off, thanks for creating a wonderful application!  I've used the R code & found it works well.  The only issue I have is the length of time pTFCE takes to execute in R.  Is there a way to speed it up?  Alternatively, if we could simply supply a Z-stat image & mask to MATLAB, instead of the .mat file this might also help speed things up.  

Thanks again,

John

**Comment by spisakt** [comment]
Hi John, thanks for your interest!

Good news: we are working on the C++ implementation which will be super-fast! Feel free to follow me here, or on Twitter (@spisaktamas) to get notified about possible releases in the upcoming months.

It is possible to use the SPM Toolbox without the SPM.mat file. Have a look at the pTFCE.m source file. The pTFCE Matlab function works pretty similar to the R-function, except that it cannot estimate image smoothness (uses the values from SPM), so you have to compute the Rd and V values externally, e.g. with the R-package or with FSL's smoothest (see this [link](https://github.com/spisakt/pTFCE/wiki/Some-important-notes-on-smoothness-estimation)). However, I don't think that the Matlab code would be much faster than the R-implementation.

I would be glad if you could provide me some running times (together with the number of voxels in your mask), since recently I was notified about speed-issues in some cases.

Cheers,
Tamas
