### ISSUE TITLE
Error in seq.default(logpmin, logpmax, length.out = Nh) :    'to' must be a finite number

### ISSUE THREAD

**Issue by matthigger** [spisakt/pTFCE#3]
I'm struggling with what looks like a numerical issue.  Running this stat file and mask seem to get me in trouble:

```
library(oro.nifti) 
library(pTFCE) 
Z=readNIfTI('stat.nii.gz') 
MASK=readNIfTI('mask.nii.gz') 
pTFCE=ptfce(Z, MASK) 
```
> Estimating smoothness based on the data...
>   |=============================================================| 100%
> Error in seq.default(logpmin, logpmax, length.out = Nh) : 
>   'to' must be a finite number

here are the files I'm working with.  I checked to ensure all values are above board, the statistic is positive across the whole mask.

[mask.nii.gz](https://github.com/spisakt/pTFCE/files/3015259/mask.nii.gz)
[stat.nii.gz](https://github.com/spisakt/pTFCE/files/3015260/stat.nii.gz)

(Also, thanks for the great software! the download / install / test example all went beautifully)

**Comment by spisakt** [comment]
Hi @matthigger,
Are you sure your input is a valid z-score image?
It does not look like any real data application I have seen before.
You have some unrealistically high Z-scores, that's why pTFCE crashes with overflow.

Depending on hardware, Z-score greater than about 35 will cause this error.
If you are sure that you want to enhance this map, consider truncating Z values at a reasonable level.
It shouldn't affect the results of the enhancement very much.

Cheers,
Tamas

**Comment by spisakt** [comment]
Hi Matt,
Please note that pTFCE is only valid with Z-scores as input!
Otherwise you are right, practically no enhancement is needed for very high peaks, thus truncating peaks to e.g. 30 will still do the job and enhnace low-intensity border regions equally well.

Cheers,
Tamas

**Comment by matthigger** [comment]
Hi Tamas,

Sorry, I misunderstood that bit.  I'll be sure to represent it as a Z score in the analysis.

Best,

-Matt
